[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "polars-cnlp"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "polars",
]
readme = "README.md"
license = "MIT"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Rust",
]

[project.urls]
Home = "https://github.com/kpwhri/polars_cnlp"
Changelog = "https://github.com/kpwhri/polars_cnlp/blob/master/CHANGELOG.md"
Issues = "https://github.com/kpwhri/polars_cnlp/issues"

[tool.maturin]
python-source = "python"
module-name = "polars_cnlp._polars_cnlp"